apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: process_queue
  name: process_queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: process_queue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: process_queue
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z doctolib_redis-master.default.svc.cluster.local 6379; do echo waiting for redis; sleep 2; done;",
            ]
      containers:
        - name: process_queue
          image: mobidyc/doctoprocess:latest
          envFrom:
            - secretRef:
                name: env-secret
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 5Gi
      restartPolicy: Always
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: accelerator
                    operator: In
                    values:
                      - nvidia
